# Generated by Django 5.0.6 on 2024-06-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='cheked',
            new_name='checked',
        ),
    ]
